name: Deploy Docs

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        run: |
          pip install -r requirements/requirements-docs.txt
      - name: Install boost
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev
      - name: Compile ebtel++
        run: |
          scons
      - name: Build Docs
        run: |
          cd docs
          make
          cd ..
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/site