name: synthesizar-dev
channels:
- defaults
- conda-forge
dependencies:
- python
- pip
- numba
- sunpy
- dask
- distributed
- yt
- flake8
- sphinx
- zarr
- asdf
- pip:
  - sphinx-astropy
  - plasmapy[theory]
  - git+git://github.com/wtbarnes/fiasco.git
  - git+git://github.com/rice-solar-physics/pydrad.git
